### ISSUE TITLE
Ucomment sponsorship logos code and populate with logos

### ISSUE THREAD

**Issue by amitSA** [CruzHacks/cruzhacks-react#3]
Link to Logos: 
https://drive.google.com/drive/u/0/folders/1Y2BfaCq2VEaiZYnVdjt-gZHL_2BzM0a5

Karthik said he has the code for logos uncommitted out in the frontend.  We just need someone to attach the logo files into the respective slots.

How should look visually: https://www.figma.com/file/S9rdIaZmHmnyZ8qvgEJiyDqh/CruzHacks-Website?node-id=262%3A3&redirected=1

**Comment by kartmanny** [comment]
Will take care of this
