### ISSUE TITLE
Add Pre-hack workshop notification on landing near hero

### ISSUE THREAD

**Issue by amitSA** [CruzHacks/cruzhacks-react#33]
Discussed with @greg-wolff on where to notify attendees for pre-hack workshops. 
Greg suggested a notification like this `[NEW] Sign up for pre-hack workshops]` which will redirect to a google form with a schedule and sign up for all pre-hack workshops
![image](https://user-images.githubusercontent.com/7193781/48295334-d1e02380-e43f-11e8-8cda-c3f62c07da99.png)

I'm fine with any idea that makes pre-hack workshops visible on the landing page.  We'll create a google form with descriptions, so a link to there will do

**Comment by greg-wolff** [comment]
closed by #35
