### ISSUE TITLE
Add UCSC Checkbox to the hacker application form

### ISSUE THREAD

**Issue by amitSA** [CruzHacks/cruzhacks-react#43]
In the hacker application form we need to ask if they are UCSC students and then force their ucsc email
@amicks  can you update the hacker schema ?
@kartmanny can you update the frontent ?

This is important to do, because we need to know whose a UCSC student or not for statistics and acceptances.  We can look at resumes to determine this, but that's a pain to do and we won't be able to query on this property then.

**Comment by kartmanny** [comment]
We can get this info from university and email fields
