### ISSUE TITLE
Add deadline for Hacker apps on landing page

### ISSUE THREAD

**Issue by amitSA** [CruzHacks/cruzhacks-react#49]
We've received a lot of feedback on this, and it will be really helpful to put deadlines on the page.  
At the Dec 2nd organizer meeting we decided on having in state apps close on December 31st.
Have out-of-state apps close on December 15th.

**Comment by amitSA** [comment]
Say in the hacker application description that we will be doing rolling acceptances so it's best hackers apply sooner than later

**Comment by kartmanny** [comment]
Fixed
